on: [push]
jobs:
  build:
    name: Run Jmeter test
    runs-on: ubuntu-latest
    steps:
    - name: JMeter Test
      uses: QAInsights/PerfAction@v3.1
      with:
          test-plan-path: Mastery_Final_GraphQL.jmx
    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
       filename: jmeter-results
       path: jmeter.jtl
